server {
    listen 80;

    # Servir los archivos de React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Necesario para que funcione el routing de React
        try_files $uri $uri/ /index.html;
    }

    # Redirigir llamadas /api al backend
    # Así el frontend llama a /api/... y Nginx lo manda al contenedor backend
    location /api/ {
        proxy_pass http://backend:3001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }
}
